FlowswitchApplication/Models/Flowswitch.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowswitchApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flowswitch
    {
        public Flowswitch()
        {
            this.CalibrationRecords = new HashSet<CalibrationRecord>();
            this.FlowswitchNotes = new HashSet<FlowswitchNote>();
        }
    
        public int ID { get; set; }
        public int AreaID { get; set; }
        public int LocationID { get; set; }
        public int VenturiID { get; set; }
        public int WaterID { get; set; }
        public int SubsystemID { get; set; }
        public int TypeID { get; set; }
        public int DetailID { get; set; }
        public string Name { get; set; }
        public string Alias { get; set; }
        public Nullable<int> FlowswitchMakeID { get; set; }
        public Nullable<int> FlowswitchModelID { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual ICollection<CalibrationRecord> CalibrationRecords { get; set; }
        public virtual FlowswitchMake FlowswitchMake { get; set; }
        public virtual FlowswitchModel FlowswitchModel { get; set; }
        public virtual Location Location { get; set; }
        public virtual SubSystem SubSystem { get; set; }
        public virtual FlowswitchType FlowswitchType { get; set; }
        public virtual Venturi Venturi { get; set; }
        public virtual WaterSource WaterSource { get; set; }
        public virtual ICollection<FlowswitchNote> FlowswitchNotes { get; set; }
    }
}

FlowswitchApplication/Models/FlowswitchType.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowswitchApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowswitchType
    {
        public FlowswitchType()
        {
            this.Flowswitches = new HashSet<Flowswitch>();
        }
    
        public int ID { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<Flowswitch> Flowswitches { get; set; }
    }
}

FlowswitchApplication/Controllers/FlowswitchController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FlowswitchApplication.Models;
using PagedList;
using FlowswitchApplication.ViewModels;

namespace FlowswitchApplication.Controllers
{
   [Authorize]
    public class FlowswitchController : Controller
    {
        private flowswitch_dbEntities db = new flowswitch_dbEntities();

        // GET: Flowswitch
        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "Name" : "";
            ViewBag.AreaIDSortParm = String.IsNullOrEmpty(sortOrder) ? "AreaID" : "";
            ViewBag.LocationIDSortParm = String.IsNullOrEmpty(sortOrder) ? "LocationID" : "";
            ViewBag.SubsystemIDSortParm = String.IsNullOrEmpty(sortOrder) ? "SubsystemID" : "";
            ViewBag.WaterIDSortParm = String.IsNullOrEmpty(sortOrder) ? "WaterID" : "";
            ViewBag.SubsystemIDSortParm = String.IsNullOrEmpty(sortOrder) ? "SubsystemID" : "";
           
             
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;


            var flowswitches = db.Flowswitches.Include(f => f.Area).Include(f => f.FlowswitchMake).Include(f => f.FlowswitchModel).Include(f => f.Location).Include(f => f.SubSystem).Include(f => f.FlowswitchType).Include(f => f.Venturi).Include(f => f.WaterSource);
            if (!String.IsNullOrEmpty(searchString))
            {
                flowswitches = flowswitches.Where(f => f.Name.Contains(searchString)
                                       || f.Alias.Contains(searchString)
                                       || f.Area.Area1.Contains(searchString)
                                       || f.Location.Location1.Contains(searchString)
                                       || f.SubSystem.Acronym.Contains(searchString)
                                       || f.WaterSource.Source.Contains(searchString));
            }
           
            
            switch (sortOrder)
            {
                case "Name":
                    flowswitches = flowswitches.OrderByDescending(f => f.Name);
                    break;
                case "AreaID":
                    flowswitches = flowswitches.OrderByDescending(f => f.AreaID);
                    break;
                case "LocationID":
                    flowswitches = flowswitches.OrderByDescending(f => f.LocationID);
                    break;
                case "SubsystemID":
                    flowswitches = flowswitches.OrderByDescending(f => f.SubsystemID);
                    break;
                case "WaterID":
                    flowswitches = flowswitches.OrderByDescending(f => f.WaterID);
                    break;
                default:
                    flowswitches = flowswitches.OrderBy(f => f.ID);
                    break;

            }


            int pageSize = 20;
            int pageNumber = (page ?? 1);
            return View(flowswitches.ToPagedList(pageNumber, pageSize));
        }

        // GET: Flowswitch/Details/5
        public ActionResult Details(int? id)
        {
            
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Flowswitch flowswitches = db.Flowswitches.Find(id);
            if (flowswitches == null)
            {
                return HttpNotFound();
            }
            return View(flowswitches);

            //string flowswitchString = id.ToString();
           // String query = "SELECT COUNT(ID) CalibrationRecords WHERE FlowswitchID ="+ flowswitches;
            //var data = db.Database.SqlQuery<CalibrationRecordGroup>(query);
            //ViewBag.CalibrationCount = data;
            
            
            //var result = db.Flowswitches.SqlQuery(query, id);

        }
        // GET: FlowswitchesController/Create
        public ActionResult Create()
        {
            ViewBag.AreaID = new SelectList(db.Areas, "ID", "Area1");
            ViewBag.FlowswitchMakeID = new SelectList(db.FlowswitchMakes, "ID", "Make");
            ViewBag.FlowswitchModelID = new SelectList(db.FlowswitchModels, "ID", "Model");
            ViewBag.LocationID = new SelectList(db.Locations, "ID", "Location1");
            ViewBag.SubsystemID = new SelectList(db.SubSystems, "ID", "Acronym");
            ViewBag.TypeID = new SelectList(db.FlowswitchTypes, "ID", "Type");
            ViewBag.VenturiID = new SelectList(db.Venturis, "ID", "Type");
            ViewBag.WaterID = new SelectList(db.WaterSources, "ID", "Source");
            //return View();
            return PartialView("_Create");
        }

        // POST: FlowswitchesController/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,AreaID,LocationID,VenturiID,WaterID,SubsystemID,TypeID,DetailID,Name,Alias,FlowswitchMakeID,FlowswitchModelID")] Flowswitch flowswitch)
        {
            if (ModelState.IsValid)
            {
                db.Flowswitches.Add(flowswitch);
                db.SaveChanges();
                //return RedirectToAction("Index");
                return Json(new { success = true });
            }

            ViewBag.AreaID = new SelectList(db.Areas, "ID", "Area1", flowswitch.AreaID);
            ViewBag.FlowswitchMakeID = new SelectList(db.FlowswitchMakes, "ID", "Make", flowswitch.FlowswitchMakeID);
            ViewBag.FlowswitchModelID = new SelectList(db.FlowswitchModels, "ID", "Model", flowswitch.FlowswitchModelID);
            ViewBag.LocationID = new SelectList(db.Locations, "ID", "Location1", flowswitch.LocationID);
            ViewBag.SubsystemID = new SelectList(db.SubSystems, "ID", "Acronym", flowswitch.SubsystemID);
            ViewBag.TypeID = new SelectList(db.FlowswitchTypes, "ID", "Type", flowswitch.TypeID);
            ViewBag.VenturiID = new SelectList(db.Venturis, "ID", "Type", flowswitch.VenturiID);
            ViewBag.WaterID = new SelectList(db.WaterSources, "ID", "Source", flowswitch.WaterID);
            //return View(flowswitch);
            return PartialView("_Create", flowswitch);
        }
        // GET: Flowswitche/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Flowswitch flowswitch = db.Flowswitches.Find(id);
            if (flowswitch == null)
            {
                return HttpNotFound();
            }
            ViewBag.AreaID = new SelectList(db.Areas, "ID", "Area1", flowswitch.AreaID);
            ViewBag.FlowswitchMakeID = new SelectList(db.FlowswitchMakes, "ID", "Make", flowswitch.FlowswitchMakeID);
            ViewBag.FlowswitchModelID = new SelectList(db.FlowswitchModels, "ID", "Model", flowswitch.FlowswitchModelID);
            ViewBag.LocationID = new SelectList(db.Locations, "ID", "Location1", flowswitch.LocationID);
            ViewBag.SubsystemID = new SelectList(db.SubSystems, "ID", "Acronym", flowswitch.SubsystemID);
            ViewBag.TypeID = new SelectList(db.FlowswitchTypes, "ID", "Type", flowswitch.TypeID);
            ViewBag.VenturiID = new SelectList(db.Venturis, "ID", "Type", flowswitch.VenturiID);
            ViewBag.WaterID = new SelectList(db.WaterSources, "ID", "Source", flowswitch.WaterID);
            //return View(flowswitch);
            return PartialView("_Edit");
            
        }

        // POST: Flowswitche/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,AreaID,LocationID,VenturiID,WaterID,SubsystemID,TypeID,DetailID,Name,Alias,FlowswitchMakeID,FlowswitchModelID")] Flowswitch flowswitch)
        {
            if (ModelState.IsValid)
            {
                db.Entry(flowswitch).State = EntityState.Modified;
                db.SaveChanges();
                //return RedirectToAction("Index");
                //return RedirectToAction("Details", "Flowswitch", new { id = flowswitch.ID });
                return Json(new { success = true });
            }
            
            ViewBag.AreaID = new SelectList(db.Areas, "ID", "Area1", flowswitch.AreaID);
            ViewBag.FlowswitchMakeID = new SelectList(db.FlowswitchMakes, "ID", "Make", flowswitch.FlowswitchMakeID);
            ViewBag.FlowswitchModelID = new SelectList(db.FlowswitchModels, "ID", "Model", flowswitch.FlowswitchModelID);
            ViewBag.LocationID = new SelectList(db.Locations, "ID", "Location1", flowswitch.LocationID);
            ViewBag.SubsystemID = new SelectList(db.SubSystems, "ID", "Acronym", flowswitch.SubsystemID);
            ViewBag.TypeID = new SelectList(db.FlowswitchTypes, "ID", "Type", flowswitch.TypeID);
            ViewBag.VenturiID = new SelectList(db.Venturis, "ID", "Type", flowswitch.VenturiID);
            ViewBag.WaterID = new SelectList(db.WaterSources, "ID", "Source", flowswitch.WaterID);
            //return View(flowswitch);

FlowswitchApplication/Views/Flowswitch/Details.cshtml
@model FlowswitchApplication.Models.Flowswitch

@{
    ViewBag.Title = "Details";
}
@Html.Partial("NavBarPartial")

<br />
<h1 class="bottom-border">@Html.DisplayFor(model => model.Name)</h1>

<h3>details</h3>

<div class="row bottom-border">
    <div class="col-xs-4 col-md-2">
        <div>
            <button class="btn btn-toolbar btn-md" type="button" style="background-color:transparent; border-color:transparent; outline:hidden" data-toggle="collapse" data-target="#details" aria-expanded="true" aria-controls="calibrationRecords">
                view <span class="glyphicon glyphicon-menu-down"></span>
            </button>
        </div>
    </div>
    <div class="col-xs-4 col-md-2">
        <div>
            <span>
                <a class="btn btn-toolbar btn-md" type="button" href='@Url.Action("Edit", "Flowswitch", new { id = Model.ID })' data-toggle="modal" , data-target="#myModal" style="background-color:transparent; border-color:transparent; outline:hidden">
                    edit  <span class="glyphicon glyphicon-edit"></span>
                </a>
            </span>
        </div>
    </div>
</div>

<div class=" collapse" id="details">
    <div class="well">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h2 class="panel-title"><strong>@Html.DisplayFor(model => model.Name)</strong></h2>

            </div>
            <div class="panel-body">

                <dl class="dl-horizontal">

                    <dt>Name: </dt>
                    <dd>@Html.DisplayFor(model => model.Name)</dd>
                    <dt>Alias: </dt>
                    <dd>@Html.DisplayFor(model => model.Alias)</dd>
                    <dt>Area: </dt>
                    <dd>@Html.DisplayFor(model => model.Area.Area1)</dd>
                    <dt>Make: </dt>
                    <dd>@Html.DisplayFor(model => model.FlowswitchMake.Make)</dd>
                    <dt>Model: </dt>
                    <dd>@Html.DisplayFor(model => model.FlowswitchModel.Model)</dd>
                    <dt>Location: </dt>
                    <dd>@Html.DisplayFor(model => model.Location.Location1)</dd>
                    <dt>SubSystem: </dt>
                    <dd>@Html.DisplayFor(model => model.SubSystem.Acronym)</dd>
                    <dt>Type: </dt>
                    <dd>@Html.DisplayFor(model => model.FlowswitchType.Type)</dd>
                    <dt>Venturi: </dt>
                    <dd>@Html.DisplayFor(model => model.Venturi.Type)</dd>
                    <dt>Source: </dt>
                    <dd>@Html.DisplayFor(model => model.WaterSource.Source)</dd>
                </dl>
            </div>
        </div>
        <button class="btn btn-toolbar btn-md" type="button" style="background-color:transparent; outline:hidden; border-color:transparent" data-toggle="collapse" data-target="#details" aria-expanded="true" aria-controls="calibrationRecords">
            close <span class="glyphicon glyphicon-menu-up"></span>
        </button>
    </div>
</div>
<br />
<span class="h3">notes <span class="badge alert-warning" style="font-size:small">@{Html.RenderAction("FlowswitchNoteCount", "Flowswitch", new { id = Model.ID });}</span></span>
<div class="row bottom-border">
    <div class="col-xs-4 col-md-2">
        <div>
            <button class="btn btn-toolbar btn-md" type="button" style="background-color:transparent; border-color:transparent; outline:hidden" data-toggle="collapse" data-target="#notes" aria-expanded="true" aria-controls="calibrationRecords">
                view <span class="glyphicon glyphicon-menu-down"></span>
            </button>
        </div>
    </div>
    <div class="col-xs-4 col-md-2">
        <div>
            <span>
                <a class="btn btn-toolbar btn-md" type="button" href='@Url.Action("Create", "FlowswitchNotes", new { FlowswitchID = Model.ID })' data-toggle="modal" , data-target="#myModal" style="background-color:transparent; border-color:transparent; outline:hidden">
                    add new  <span class="glyphicon glyphicon-plus"></span>
                </a>
            </span>
        </div>
    </div>
</div>

<div class="collapse" id="notes">
    <div class="well">
        <h4>@Html.DisplayFor(model => model.Name)</h4>
        <table class="table table-hover hidden-xs h5">
            <tr>
                <th class="col-sm-1">Date</th>
                <th class="col-sm-2">Technician</th>
                <th class="col-xs-1 hidden-xs">Note</th>
                <th></th>
            </tr>
            @foreach (var item in Model.FlowswitchNotes.Reverse())
            {
                <tr class='clickable-row' data href="@Url.Action("xxx", "Details", new { id = item.ID})">
                    <td>@Html.DisplayFor(modelItem => item.DateAdded)</td>
                    <td>@Html.DisplayFor(modelItem => item.Technician.FirstName) @Html.DisplayFor(modelItem => item.Technician.LastName)</td>
                    <td>@Html.DisplayFor(modelItem => item.Note)</td>
                    
                    <td>
                        <a href='@Url.Action("Details", "FlowswitchNotes", new { id = item.ID})' data-toggle="modal" data-target="#myModal" style="outline:hidden; color:white" class="btn btn-info btn-xs">
                            View
                        </a>
                    <td>
                       
                </tr>
            }
        </table>
        @foreach (var item in Model.FlowswitchNotes.Reverse())
        {
            <div class="panel panel-default hidden-lg hidden-md hidden-sm">
                <div class="panel-heading">
                    <h2 class="panel-title">@Html.DisplayFor(modelItem => item.DateAdded)</h2>
                    <h2 class="panel-title">@Html.DisplayFor(modelItem => item.Technician.FirstName) @Html.DisplayFor(modelItem => item.Technician.LastName)</h2>
                </div>
                <div class="row">
                    <div class="col-md-12" style="padding:15px">
                        <dl class="dl-horizontal">
                            <dt>Note:</dt>
                            <dd>@Html.DisplayFor(modelItem => item.Note)</dd>
                        </dl>
                        
                        <div style="padding-left:35px; padding-bottom:25px">
                            <a href='@Url.Action("Details", "FlowswitchNotes", new { id = item.ID})' data-toggle="modal" data-target="#myModal" style="outline:hidden; color:white" class="btn btn-info btn-xs">
                                View
                            </a>
                        </div>
                            
                    </div>

                    @*<div style="padding-left:35px; padding-bottom:25px">@Html.ActionLink("View", "Details", "CalibrationRecord", new { id = item.ID }, new { @class = "btn btn-info btn-sm", @style = "color:white" })</div>*@
                </div>
            </div>
        }
        <div>
            <button class="btn btn-toolbar btn-md" type="button" style="background-color:transparent; outline:hidden; border-color:transparent" data-toggle="collapse" data-target="#notes" aria-expanded="true" aria-controls="calibrationRecords">
                close <span class="glyphicon glyphicon-menu-up"></span>
            </button>
        </div>
        
    </div>
</div>
<br />
<span class="h3">records <span class="badge alert-danger" style="font-size:small">@{Html.RenderAction("CalibrationRecordCount", "Flowswitch", new { id = Model.ID });}</span></span>

<div class="row bottom-border">
    <div class="col-xs-4 col-md-2">
        <div>
            <button class="btn btn-toolbar btn-md" type="button" style="background-color:transparent; border-color:transparent; outline:hidden" data-toggle="collapse" data-target="#calibrationRecords" aria-expanded="true" aria-controls="calibrationRecords">
                view <span class="glyphicon glyphicon-menu-down"></span>
            </button>
        </div>
    </div>
    <div class="col-xs-4 col-md-2">
        <div>
            <span>
                <a class="btn btn-toolbar btn-md" type="button" href='@Url.Action("Create", "CalibrationRecord", new { FlowswitchID = Model.ID })' data-toggle="modal" , data-target="#myModal" style="background-color:transparent; border-color:transparent; outline:hidden">
                    add new  <span class="glyphicon glyphicon-plus"></span>
                </a>
            </span>
        </div>
    </div>
</div>

<div class="collapse" id="calibrationRecords">
    <div class="well">
        <h4>@Html.DisplayFor(model => model.Name)</h4>
        <table class="table table-hover hidden-xs h5">
            <tr>
                <th class="col-sm-1">Date</th>
                <th class="col-sm-2">Technician</th>
                <th class="col-xs-1 hidden-xs">Trip Inches</th>
                <th class="col-sxs-1 hidden-xs">Trip Galllons</th>
                <th class="col-xs-1 hidden-xs">Max Inches</th>
                <th class="col-sxs-1 hidden-xs">Max Gallons</th>
                <th class="col-sm-4">Calibration Note</th>
                <th class="col-sm-1">                </th>
            </tr>
            @foreach (var item in Model.CalibrationRecords.Reverse())
            {
                <tr class='clickable-row' data href="@Url.Action("xxx", "Details", new { id = item.ID})">
                    <td>@Html.DisplayFor(modelItem => item.DateAdded)</td>
                    <td>@Html.DisplayFor(modelItem => item.Technician.FirstName) @Html.DisplayFor(modelItem => item.Technician.LastName)</td>
                    <td class="hidden-xs">@Html.DisplayFor(modelItem => item.TripInches)</td>
                    <td class="hidden-xs">@Html.DisplayFor(modelItem => item.TripGallons)</td>
                    <td class="hidden-xs">@Html.DisplayFor(modelItem => item.MaxInches)</td>
                    <td class="hidden-xs">@Html.DisplayFor(modelItem => item.MaxGallons)</td>
                    <td>@Html.DisplayFor(modelItem => item.Note)</td>
                    <td>
                        <a href='@Url.Action("Details", "CalibrationRecord", new { id = item.ID})' data-toggle="modal" data-target="#myModal" style="outline:hidden; color:white" class="btn btn-info btn-xs">
                            View
                        </a>
                    <td>
                </tr>
            }
        </table>
        @foreach (var item in Model.CalibrationRecords.Reverse())
        {
            <div class="panel panel-default hidden-lg hidden-md hidden-sm">
                <div class="panel-heading">
                    <h2 class="panel-title">@Html.DisplayFor(modelItem => item.DateAdded)</h2>
                    <h2 class="panel-title">@Html.DisplayFor(modelItem => item.Technician.FirstName) @Html.DisplayFor(modelItem => item.Technician.LastName)</h2>
                </div>
                <div class="row">
                    <div class="col-md-12" style="padding:15px">
                        <dl class="dl-horizontal">
                            <dt>Trip Inches: </dt>
                            <dd>@Html.DisplayFor(modelItem => item.TripInches)</dd>
                            <dt>Max Inches: </dt>
                            <dd>@Html.DisplayFor(modelItem => item.MaxInches)</dd>
                            <dt>Trip Gallons: </dt>
                            <dd>@Html.DisplayFor(modelItem => item.TripGallons)</dd>
                            <dt>Max Gallons: </dt>
                            <dd>@Html.DisplayFor(modelItem => item.MaxGallons)</dd>
                            <dt>Note:</dt>
                            <dd>@Html.DisplayFor(modelItem => item.Note)</dd>
                        </dl>
                        <div style="padding-left:35px; padding-bottom:25px">
                            <a href='@Url.Action("Details", "CalibrationRecord", new { id = item.ID})' data-toggle="modal" data-target="#myModal" style="outline:hidden; color:white" class="btn btn-info btn-xs">
                                View
                            </a>
                        </div> 
                    </div>
                                   
                    @*<div style="padding-left:35px; padding-bottom:25px">@Html.ActionLink("View", "Details", "CalibrationRecord", new { id = item.ID }, new { @class = "btn btn-info btn-sm", @style = "color:white" })</div>*@
                </div>
            </div>
        }
        <div>
            <button class="btn btn-toolbar btn-md" type="button" style="background-color:transparent; outline:hidden; border-color:transparent" data-toggle="collapse" data-target="#calibrationRecords" aria-expanded="true" aria-controls="calibrationRecords">
                close <span class="glyphicon glyphicon-menu-up"></span>
            </button>
        </div>
    </div>
</div>





<br />
@*<div>@Html.ActionLink("Back to List", "Index", new { id = Model.ID }, new { @class = "btn btn-default btn-sm" })</div>*@
<input type="button" value="Back to List" onclick="history.go(-1); return false;" class="btn btn-default btn-sm" />

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/modalform")
}


FlowswitchApplication/Views/Flowswitch/Index.cshtml
@model PagedList.IPagedList<FlowswitchApplication.Models.Flowswitch>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Flowswitches";
}
@Html.Partial("NavBarPartial")


<div class="row" style="padding-bottom:10px">
    <div class="col-sm-6">
        <h2 style="padding-top:20px">Flow Switches</h2>
    </div>
</div>
<div class="row">
    <div class="col-sm-6">
        <div class="input-group custom-search-form classTextWithPad">
            <span class="input-group-btn btn-group-sm">
                <button class="btn btn-default btn-sm" type="button">
                    <span class="glyphicon glyphicon-search"></span>
                </button>
            </span>
            @using (Html.BeginForm())
            {@Html.TextBox("SearchString", "", new { @class = "form-control", @placeholder = "search all fields...", @style = "height:36px; font-size:12px" })}
        </div>
    </div>
</div>
<div class="row" style="padding:20px">
    <div class="col-sm-push-6">
        @Html.ActionLink("Add new flow switch", "Create", "Flowswitch", new { data_modal = " " })
        @*@Html.ActionLink("Add new flow switch", "Create", new { @class = "btn btn-success btn-xs", @style = "color:white" })*@
    </div>
</div>

<table class="table table-hover h5">
    <tr>
        <th>
            @Html.ActionLink("Name", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Area", "Index", new { sortOrder = ViewBag.AreaIDSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Location", "Index", new { sortOrder = ViewBag.LocationIDSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <!--<th>
            @Html.ActionLink("Subsystem", "Index", new { sortOrder = ViewBag.SubsystemIDSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>-->
        <th>
            @Html.ActionLink("Source", "Index", new { sortOrder = ViewBag.WaterIDSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        @*<th>
            @Html.ActionLink("CalibrationCount", "Index", new { sortOrder = ViewBag.CalibrationCountSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>*@
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>

                @Html.ActionLink(item.Name, "Details", new { id = item.ID })<br />
                <span style="font-size:10px">{@{Html.RenderAction("CalibrationRecordCount", "Flowswitch", new { id = item.ID });} records}</span>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Area.Area1)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Location.Location1)
            </td>
            <!--<td>
                @Html.DisplayFor(modelItem => item.SubSystem.Acronym)
            
            <td  class="hidden-lg hidden-md hidden-sm">
                @Html.DisplayFor(modelItem => item.WaterSource.Source)
                <p>@Html.ActionLink("Details", "Details", new { id = item.ID }, new { @class = "btn btn-info btn-xs", @style = "color:white" })</p>
            </td>
               -->
            <td>
                @Html.DisplayFor(modelItem => item.WaterSource.Source)
            </td>
            @*<td>
                @{Html.RenderAction("CalibrationRecordCount", "Flowswitch", new { id = item.ID });}
            </td>*@
            <td class="hidden-xs">
                @Html.ActionLink("Details", "Details", new { id = item.ID }, new { @class = "btn btn-info btn-xs", @style = "color:white" })

            </td>
        </tr>
    }

</table>


<br />
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/modalform")
}