FlowswitchApplication/Models/CalibrationRecord.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowswitchApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalibrationRecord
    {
        public int ID { get; set; }
        public string MaxInches { get; set; }
        public string MaxGallons { get; set; }
        public string TripInches { get; set; }
        public string TripGallons { get; set; }
        public Nullable<int> TechnicianID { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public int FlowswitchID { get; set; }
        public string Note { get; set; }
        public Nullable<int> ServiceRequestID { get; set; }
    
        public virtual Flowswitch Flowswitch { get; set; }
        public virtual ServiceRequest ServiceRequest { get; set; }
        public virtual Technician Technician { get; set; }
    }
}

FlowswitchApplication/Controllers/CalibrationRecordController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FlowswitchApplication.Models;
using PagedList;

namespace FlowswitchApplication.Controllers
{
    [Authorize]
    public class CalibrationRecordController : Controller
    {
        private flowswitch_dbEntities db = new flowswitch_dbEntities();

        // GET: CalibrationRecord
        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.DateSortParm = sortOrder == "Date" ? "DateAdded" : "Date";
            ViewBag.TechnicianIDSortParm = String.IsNullOrEmpty(sortOrder) ? "TechnicianID" : "";
            ViewBag.FlowswitchIDSortParm = String.IsNullOrEmpty(sortOrder) ? "FlowswitchID" : "";
            

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;


            var calibrationRecords = db.CalibrationRecords.Include(c => c.Technician).Include(c => c.Flowswitch).Include(c => c.ServiceRequest);
            if (!String.IsNullOrEmpty(searchString))
            {
                calibrationRecords = calibrationRecords.Where(c => c.Technician.FirstName.Contains(searchString)
                                       || c.Technician.LastName.Contains(searchString)
                                       || c.Technician.Username.Contains(searchString)
                                       || c.Flowswitch.Name.Contains(searchString)
                                       || c.Note.Contains(searchString)
                                       || c.ServiceRequest.Cater.Contains(searchString)
                                       || c.ServiceRequest.FamisWorkOrder.Contains(searchString));
                                       
            }

            switch (sortOrder)
            {
                case "DateAdded":
                    calibrationRecords = calibrationRecords.OrderByDescending(c => c.DateAdded);
                    break;
                case "TechnicianID":
                    calibrationRecords = calibrationRecords.OrderByDescending(c => c.TechnicianID);
                    break;
                case "FlowswitchID":
                     calibrationRecords = calibrationRecords.OrderByDescending(c => c.FlowswitchID);
                    break;
                default:
                    calibrationRecords = calibrationRecords.OrderByDescending(c => c.DateAdded);
                    break;

            }


            int pageSize = 60;
            int pageNumber = (page ?? 1);
            return View(calibrationRecords.ToPagedList(pageNumber, pageSize));
        }
        // GET: CalibrationRecord/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CalibrationRecord calibrationRecord = db.CalibrationRecords.Find(id);
            if (calibrationRecord == null)
            {
                return HttpNotFound();
            }
            //return View(calibrationRecord);
            return PartialView("_Details",calibrationRecord);
        }

        // GET: CalibrationRecord/Create
        public ActionResult Create(int? flowswitchID)
        {
            if (flowswitchID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Flowswitch flowswitches = db.Flowswitches.Find(flowswitchID);
            ViewBag.ID = flowswitchID;
            ViewBag.Name = flowswitches.Name;


            ViewBag.FlowswitchID = flowswitchID;// new SelectList(db.Flowswitches, "ID", "Name");
            ViewBag.ServiceRequestID = new SelectList(db.ServiceRequests, "ID", "FamisWorkOrder");
            ViewBag.TechnicianID = new SelectList(db.Technicians, "ID", "LastName");
            //return View();
            return PartialView("_Create");
        }

        // POST: CalibrationRecord/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( int? flowswitchID,[Bind(Include = "ID,MaxInches,MaxGallons,TripInches,TripGallons,TechnicianID,DateAdded,FlowswitchID,Note,ServiceRequestID")] CalibrationRecord calibrationRecord)
        {
            if (ModelState.IsValid)
            {
                db.CalibrationRecords.Add(calibrationRecord);
                db.SaveChanges();
                return RedirectToAction("Details", "Flowswitch", new { id = flowswitchID});
                //return Json(new { success = true });
            }

            ViewBag.FlowswitchID = flowswitchID;// new SelectList(db.Flowswitches, "ID", "Name", calibrationRecord.FlowswitchID);
            ViewBag.ServiceRequestID = new SelectList(db.ServiceRequests, "ID", "FamisWorkOrder", calibrationRecord.ServiceRequestID);
            ViewBag.TechnicianID = new SelectList(db.Technicians, "ID", "LastName", calibrationRecord.TechnicianID);
            //return View(calibrationRecord);
            return PartialView("_Create", calibrationRecord);
        }

        // GET: CalibrationRecord/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CalibrationRecord calibrationRecord = db.CalibrationRecords.Find(id);
            if (calibrationRecord == null)
            {
                return HttpNotFound();
            }
            ViewBag.FlowswitchID = new SelectList(db.Flowswitches, "ID", "Name", calibrationRecord.FlowswitchID);
            ViewBag.ServiceRequestID = new SelectList(db.ServiceRequests, "ID", "FamisWorkOrder", calibrationRecord.ServiceRequestID);
            ViewBag.TechnicianID = new SelectList(db.Technicians, "ID", "LastName", calibrationRecord.TechnicianID);
            return View(calibrationRecord);
        }

        // POST: CalibrationRecord/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,MaxInches,MaxGallons,TripInches,TripGallons,TechnicianID,DateAdded,FlowswitchID,Note,ServiceRequestID")] CalibrationRecord calibrationRecord)
        {
            if (ModelState.IsValid)
            {
                db.Entry(calibrationRecord).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", "Flowswitch", new { id = calibrationRecord.FlowswitchID });
            }
            ViewBag.FlowswitchID = new SelectList(db.Flowswitches, "ID", "Name", calibrationRecord.FlowswitchID);
            ViewBag.ServiceRequestID = new SelectList(db.ServiceRequests, "ID", "FamisWorkOrder", calibrationRecord.ServiceRequestID);
            ViewBag.TechnicianID = new SelectList(db.Technicians, "ID", "LastName", calibrationRecord.TechnicianID);
            return View(calibrationRecord);
        }

         //GET: CalibrationRecord/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CalibrationRecord calibrationRecord = db.CalibrationRecords.Find(id);
            if (calibrationRecord == null)
            {
                return HttpNotFound();
            }
            return View("Delete", calibrationRecord);
        }

        //// POST: CalibrationRecord/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CalibrationRecord calibrationRecord = db.CalibrationRecords.Find(id);
            db.CalibrationRecords.Remove(calibrationRecord);
            db.SaveChanges();
            return RedirectToAction("Details", "Flowswitch", new { id = calibrationRecord.FlowswitchID });
        }

      
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

FlowswitchApplication/Views/CalibrationRecord/Create.cshtml
@model FlowswitchApplication.Models.CalibrationRecord

@{
    ViewBag.Title = "Create";
}
@Html.Partial("NavBarPartial")
<h2>Create</h2>

@ViewBag.Name



 


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@Html.DisplayFor(model => model.Flowswitch.ID) CalibrationRecord</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <!--
        <div class="form-group">
            
            @ViewBag.Name
            @ViewBag.ID 
            
            
        </div>
            -->
        
        <div class="form-group">
            <div class = "control-label col-md-2">Flow Switch</div>
            <div class="col-md-10">
                <h5>@ViewBag.Name</h5>  
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.DateAdded, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DatePickerFor(model => model.DateAdded, "autoclose=true", "todayBtn=true", "todayHighlight=true")
                @Html.ValidationMessageFor(model => model.DateAdded, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TechnicianID, "TechnicianID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TechnicianID", null, "Select Technician", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TechnicianID, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.MaxInches, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaxInches, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaxInches, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaxGallons, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaxGallons, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaxGallons, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TripInches, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TripInches, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TripInches, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TripGallons, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TripGallons, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TripGallons, "", new { @class = "text-danger" })
            </div>
        </div>
      
        <div class="form-group">
            @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Note, new { @class = "form-control", @rows = 3 })
                @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ServiceRequestID, "ServiceRequestID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ServiceRequestID",null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ServiceRequestID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success btn-md" />
            </div>
        </div>
    </div>
}

<div>
<br />
    
    @*@Html.ActionLink("Back to List", "Details", "Flowswitch", new { id = @ViewBag.ID }, new { @class = "btn btn-default btn-sm"})*@
    <input type="button" value="Back to Details" onclick="history.go(-1); return false;" class="btn btn-default btn-sm" />
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FlowswitchApplication/Views/CalibrationRecord/Delete.cshtml
@model FlowswitchApplication.Models.CalibrationRecord

@{
    ViewBag.Title = "Delete";
}
@Html.Partial("NavBarPartial")
<h2>Delete</h2>


<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CalibrationRecord</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaxInches)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaxInches)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaxGallons)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaxGallons)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TripInches)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TripInches)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TripGallons)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TripGallons)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateAdded)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateAdded)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Note)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Note)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Flowswitch.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Flowswitch.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ServiceRequest.FamisWorkOrder)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServiceRequest.FamisWorkOrder)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Technician.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Technician.LastName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default btn-sm" /> |
            @Html.ActionLink("Back to List", "Details", "Flowswitch", new { id = Model.FlowswitchID }, new { @class = "btn btn-default btn-sm" })
        </div>
    }
</div>

FlowswitchApplication/Views/CalibrationRecord/Details.cshtml
@model FlowswitchApplication.Models.CalibrationRecord

@{
    ViewBag.Title = "Details";
    ViewBag.ID = Html.DisplayFor(model => model.Flowswitch.ID);
}
@Html.Partial("NavBarPartial")

<h2>Details</h2>

<div>
    <h4>CalibrationRecord</h4>
    <hr />
    <div>
        <ul style="list-style: none; ">
          
            <li><strong>Calibration Date:   </strong>@Html.DisplayFor(model => model.DateAdded)</li>
            <li><strong>Technician:   </strong>@Html.DisplayFor(model => model.Technician.LastName)</li>            
            <li><strong>Max Inches:   </strong>@Html.DisplayFor(model => model.MaxInches)</li>
            <li><strong>Max Gallons:   </strong>@Html.DisplayFor(model => model.MaxGallons)</li>
            <li><strong>Trip Inches:   </strong>@Html.DisplayFor(model => model.TripInches)</li>
            <li><strong>Trip Gallons:   </strong>@Html.DisplayFor(model => model.TripGallons)</li>
            <li><strong>FAMIS Work Order:  </strong>@Html.DisplayFor(model => model.ServiceRequest.FamisWorkOrder)</li>
            <li><strong>Cater:   </strong>@Html.DisplayFor(model => model.ServiceRequest.FamisWorkOrder)</li>
            <li><strong>Notes:   </strong>@Html.DisplayFor(model => model.Note)</li>
        </ul>
    </div>
    
</div>
<div class="row">
    <div class="col-md-12">
        @Html.ActionLink("Back to List", "Details", "Flowswitch", new { id = @ViewBag.ID }, new { @class = "btn btn-default btn-sm" })
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID }, new { @class = "btn btn-default btn-sm" })
        @Html.ActionLink("Delete", "Delete", new { id = Model.ID }, new { @class = "btn btn-danger btn-sm", @style = "color:white" })
    </div>
</div>

FlowswitchApplication/Views/CalibrationRecord/Edit.cshtml
@model FlowswitchApplication.Models.CalibrationRecord

@{
    ViewBag.Title = "Edit";
}
@Html.Partial("NavBarPartial")

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CalibrationRecord</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.MaxInches, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaxInches, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaxInches, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaxGallons, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaxGallons, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaxGallons, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TripInches, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TripInches, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TripInches, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TripGallons, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TripGallons, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TripGallons, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TechnicianID, "TechnicianID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TechnicianID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TechnicianID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateAdded, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateAdded, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateAdded, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FlowswitchID, "FlowswitchID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FlowswitchID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FlowswitchID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ServiceRequestID, "ServiceRequestID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ServiceRequestID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ServiceRequestID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default btn-sm" />
                |
                @Html.ActionLink("Delete", "Delete", new { id = Model.ID }, new { @class = "btn btn-danger btn-sm" })
            </div>
        </div>
    </div>
    <div>
        @Html.ActionLink("Back to List", "Details", "Flowswitch", new { id = Model.FlowswitchID }, new { @class = "btn btn-default btn-sm" })
    </div>
}

<div>
   
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FlowswitchApplication/Views/CalibrationRecord/Index.cshtml
@model PagedList.IPagedList<FlowswitchApplication.Models.CalibrationRecord>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "CalibrationRecords";
}
@Html.Partial("NavBarPartial")
<div class="row" style="padding-bottom:10px">
    <div class="col-sm-6">
        <h2>Calibration Records</h2>
    </div>
</div>
<div class="row">
    <div class="col-sm-6">
        <div class="input-group custom-search-form classTextWithPad">
            <span class="input-group-btn btn-group-sm">
                <button class="btn btn-default btn-sm" type="button">
                    <span class="glyphicon glyphicon-search"></span>
                </button>
            </span>
            @using (Html.BeginForm())
            {@Html.TextBox("SearchString", "", new { @class = "form-control", @placeholder = "search all fields...", @style = "height:36px; font-size:12px" })}
        </div>
    </div>
</div>
<div class="row" style="padding:20px">
    <div class="col-sm-push-6">

    </div>
</div>

<table class="table table-hover h5">
    <tr>
        <th class="col-sm-2">
            @Html.ActionLink("Flowswitch", "Index", new { sortOrder = ViewBag.FlowwitchIDSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th class="col-sm-1">
            @Html.ActionLink("DateAdded", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th class="col-sm-2">
            @Html.ActionLink("Technician", "Index", new { sortOrder = ViewBag.TechnicianIDSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th class="col-xs-1 hidden-xs">
            Trip Inches
        </th>
        <th class="col-sxs-1 hidden-xs">
            Trip Galllons
        </th>
        <th class="col-xs-1 hidden-xs">
            Max Inches
        </th>
        <th class="col-sxs-1 hidden-xs">
            Max Gallons
        </th>
        <th class="col-sm-4">
            Note
        </th>
        <th class="col-sm-1"></th>
    </tr>



    @foreach (var item in Model)
    {
        <tr class='clickable-row' data href="@Url.Action("xxx", "Details", new { id = item.ID})">

            <td>

                @Html.ActionLink(item.Flowswitch.Name, "Details", new { id = item.ID })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateAdded)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Technician.LastName)
            </td>
            <td class="hidden-xs">
                @Html.DisplayFor(modelItem => item.TripInches)
            </td>
            <td class="hidden-xs">
                @Html.DisplayFor(modelItem => item.TripGallons)
            </td>
            <td class="hidden-xs">
                @Html.DisplayFor(modelItem => item.MaxInches)
            </td>
            <td class="hidden-xs">
                @Html.DisplayFor(modelItem => item.MaxGallons)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Note)
            </td>
            <td class="hidden-xs">
                @Html.ActionLink("View", "Details", new { id = item.ID }, new { @class = "btn btn-info btn-xs", @style = "color:white" })
            </td>
        </tr>
    }

</table>



<br />
            Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

            @Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

FlowswitchApplication/Views/CalibrationRecord/_Details.cshtml
@model FlowswitchApplication.Models.CalibrationRecord


<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">Calibration Record Detail Modal</h4>
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="modal-body">
        
        <dl class="dl-horizontal">
            <dt>Flow Switch:     </dt>
            <dd>@Html.DisplayFor(model => model.Flowswitch.Name)</dd>
            <dt>Calibration Date:     </dt>
            <dd>@Html.DisplayFor(model => model.DateAdded)</dd>  
            <dt>Max Inches:     </dt>
            <dd>@Html.DisplayFor(model => model.MaxInches)</dd>
            <dt>Trip Inches:     </dt>
            <dd>@Html.DisplayFor(model => model.TripInches)</dd>
            <dt>Max Gallons:     </dt>
            <dd>@Html.DisplayFor(model => model.MaxGallons)</dd>
            <dt>Trip Gallons:     </dt>
            <dd>@Html.DisplayFor(model => model.TripGallons)</dd>                           
            <dt>FAMIS:     </dt>
            <dd>@Html.DisplayFor(model => model.ServiceRequest.FamisWorkOrder)</dd>
            <dt>Technician:     </dt>
            <dd>@Html.DisplayFor(model => model.Technician.LastName)</dd>
            <dt>Note:     </dt>
            <dd>@Html.DisplayFor(model => model.Note)</dd> 

        </dl>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Close</button>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID }, new { @class = "btn btn-default btn-sm" })

      
        <!--
        <a href='@Url.Action("Delete", "CalibrationRecord", new { id = Model.ID})'  data-toggle="modal" data-target="#myModal2" style="outline:hidden; color:white" class="btn btn-danger btn-sm">
            Delete
        </a>
        -->
        
</div>

}

